name: SMC CRON TEST

on:
  schedule:
    - cron: "* * * * *"   # svake minute (TEST)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run test
        run: echo "CRON WORKS - $(date)"
